# --- Stage 1: Runtime  ---
FROM nginx:alpine-slim

# Copy the built frontend files to the Nginx HTML directory
COPY html /usr/share/nginx/html

# Set non-root user for security
RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid

USER nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
