---
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: container-platform
type: Opaque
data:
  POSTGRESS_USER: cG9zdGdyZXNzX3VzZXI=  # base64 encoded value of "postgres_user"
  POSTGRESS_PASSWORD: cG9zdGdyZXNzX3Bhc3N3d29yZA==  # base64 encoded value of "postgres_password"
